package com.test.exception;

public class TestDemoException {
	//static ArithmeticException e=new ArithmeticException();
	public static void main(String[] args) throws CustomException {
		for(int  i = 1; i<=10; i++) {
			if(i%2 == 0) {
			 break;	
			}
			System.out.println(i);
		}
//		if(a<b) {
//			throw new CustomException("a value should be greater than b");
//		}
//		if(a<b) {
//			throw new CustomException();
//		}
		// TODO Auto-generated method stub
	//	System.out.println("State - 1");
		
		foo();
		//System.out.println("State - 2");
	}
 public static void foo() {
	 foo1();
 }
 public static void foo1() {
	 try {
			System.out.println(10/0);
		}catch(Exception e){
			//System.out.println(10/2);
			e.printStackTrace();
			//System.out.println(e);
			System.out.println(e);
		}
 }
}
