package com.test.exception;

public class NestedTryCatch {
//	static ArithmeticException e;
//	static ArithmeticException e = new ArithmeticException();
	public static void main(String[] args) {
		// TODO Auto-generated method stub
//		try {
//			System.out.println("State :1");
//			System.out.println("State :2" );
//			System.out.println("State :3");
//			try {
//				System.out.println("State :4");
//				System.out.println("State :5");
//				System.out.println("State :6");
//			} catch (Exception e) {
//				System.out.println("State :7");
//			} finally {
//				System.out.println("State :8");
//			}
//			System.out.println("State :9");
//		} catch (Exception e) {
//			System.out.println("State :10");
//		} finally {
//			System.out.println("State :11");
//		}
//		System.out.println("State :12"+ 10 / 0);
//		System.out.println("hello");
//		throw new ArithmeticException("/by zero");
	}

}
